### ISSUE TITLE
Speakers API

### ISSUE THREAD

**Issue by mtuchi** [pycontanzania/admin#5]
#### Description
Create a Speakers API endpoint in JSON format with fields:

- Name of the Speaker
- Their Expertise
- The Topic they wish to give
- Duration of their Talk
- Their Contact information

#### Resources
The schema of the Speakers table is available in speakers/models.py

#### Tasks

- [x] Define the Speaker Schema
- [x] Create the API endpoint

**Comment by AvicennaJr** [comment]
Created the Speakers Schema
